//THIS PROJECT IS NOT AFFILIATED WITH OR SPONSORED BY GOOGLE / GOOGLE TRANSLATE IN ANY WAY
//I needed a translation API system and "googletrans" on npm was the first reliable one I could find...
const tr = require("googletrans").default;